version: "3.8"

services:
  backend1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - SERVER_NAME=Backend1
      - PORT=3000

  backend2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - SERVER_NAME=Backend2
      - PORT=3000

  nginx-lb:
    build:
      context: ./nginx-lb
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./nginx-lb/nginx.conf:/etc/nginx/nginx.conf
